import math
import time

onoff=input("")

print ("Welcome to the Multi puropse device Version 2.0")

while onoff=="on":
	time.sleep(2)
	print ("_")
	print (" ")
	print (" ") 
	print ("Which calculator Do you want")
	time.sleep(0.5)
	print ("Use tc for trigonometric calculator")
	time.sleep(0.5)
	print ("Use sc for student calculator")
	time.sleep(0.5)
	print ("Use bc for banking calculator")
	time.sleep(0.5)
	print ("Use scc for scientific calculator")
	time.sleep(0.5)
	print ("Use cc for currency converter")
	time.sleep(2)
	calc=input("")
	if calc=="sc":
		print ("Enter a number")
		a=float(input(""))
		time.sleep(1)
		print ("Valid Operators are :")
		time.sleep(1)
		print ("+ for addition")
		time.sleep(0.5)
		print ("- for subtraction")
		time.sleep(0.5)
		print ("* for multiplication")
		time.sleep(0.5)
		print ("/ for division")
		time.sleep(0.5)
		print ("% for percentage")
		time.sleep(0.5)
		print ("< for less than")
		time.sleep(0.5)
		print ("> for greater than")
		time.sleep(0.5)
		print ("** for power")
		time.sleep(0.5)
		print ("inv for inverse")
		time.sleep(1)
		print ("Enter an operator")
		x=input("")
		b=float(input("Enter a number, (For inverse, enter 1) "))
		print ("Calculating")
		time.sleep(0.25)
		print ("Calculating.")
		time.sleep(0.25)
		print ("Calculating..")
		time.sleep(0.25)
		print ("Calculating...")
		time.sleep(0.25)
		print ("Calculating....")
		time.sleep(0.25)
		print ("Calculating.....")
		time.sleep(0.25)
		if (x=="+"):
			k=a+b
			print("answer is",k)
		elif (x=="-"):
			l=a-b
			print("answer is",l)
		elif (x=="*"):
			m=a*b
			print("answer is",m)
		elif (x=="/"):
			n=a/b
			print("answer is",n)
		elif (x=="%"):
			j=a/100
			o=j*b
			print("answer is",o)
		elif (x=="<"):
			if (a<b):
				print("It is true")
			else:
				print("It is false")
		elif (x==">"):
			if (a>b):
				print("It is true")
			else:
				print("It is false")
		elif (x=="**"):
			p=a**b
			print("answer is",p)
		elif (x=="inv"):
			print ("answer is",1/a)
		else:
			print ("Cheking for validity of Operator")
			time.sleep(2)
			print("invalid operator")
	elif calc=="tc":
		print ("Valid operators are :")
		time.sleep(0.5)
		print ("sin")
		time.sleep(0.5)
		print ("cos")
		time.sleep(0.5)
		print ("tan")
		time.sleep(0.5)
		print ("cosec")
		time.sleep(0.5)
		print ("sec")
		time.sleep(0.5)
		print ("cot")
		time.sleep(1)
		functc=input("Enter the operator ")
		time.sleep(0.5)
		angle1=float(input("Enter the angle in degrees "))
		angle=math.radians(angle1)
		a=math.sin(angle)
		b=round(a,2)
		c=math.cos(angle)
		d=round(c,2)
		e=math.tan(angle)
		f=round(e,2)
		print ("Calculating")
		time.sleep(0.25)
		print ("Calculating.")
		time.sleep(0.25)
		print ("Calculating..")
		time.sleep(0.25)
		print ("Calculating...")
		time.sleep(0.25)
		print ("Calculating....")
		time.sleep(0.25)
		print ("Calculating.....")
		time.sleep(0.25)
		if functc=="sin":
			print (b)
		if functc=="cos":
			print (d)
		if functc=="tan":
			print (f)
		if functc=="cosec":
			print (1/b)
		if functc=="sec":
			print (1/d)
		if functc=="cot":
			print (1/f)
	elif calc=="scc":
		print ("Valid operator are :")
		time.sleep(0.5)
		print ("ln for natural log")
		time.sleep(0.5)
		print ("log for log to the base 10")
		time.sleep(0.5)
		funscc=input("Enter the operator ")
		time.sleep(1)
		number=float(input("Enter the number "))
		print ("Calculating")
		time.sleep(0.25)
		print ("Calculating.")
		time.sleep(0.25)
		print ("Calculating..")
		time.sleep(0.25)
		print ("Calculating...")
		time.sleep(0.25)
		print ("Calculating....")
		time.sleep(0.25)
		print ("Calculating.....")
		time.sleep(0.25)
		if funscc=="ln":
			print (math.log(number))
		if funscc=="log":
			print (math.log10(number))
	elif calc=="bc":
		print ("Valid functions are :")
		time.sleep(0.5)
		print ("SI for simple interest")
		time.sleep(0.5)
		print ("CI for compound interest")
		time.sleep(0.5)
		funbc=input("Enter SI for simple interest and CI for compound interest ")
		if funbc=="SI":
			p=int(input("Enter Amount deposited "))
			time.sleep(0.5)
			r=float(input("Rate of Interest per annum "))
			time.sleep(0.5)
			t=int(input("Enter time period in years(Timne period should be greater than 1)"))
			i=p*r*t/100
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)
			print ("Simple Interest is")
			print (i)
			time.sleep(0.5)
			print ("Amount received after simple interest is ")
			print (i+p)
		if funbc=="CI":
			p=int(input("Enter Amount deposited "))
			time.sleep(0.5)
			r=float(input("Rate of Interest per annum"))
			time.sleep(0.5)
			n=int(input("Number of times compounded per annum"))
			time.sleep(0.5)
			t=int(input("Enter time period in years(Time period should be greater than 1)"))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			x=r/n
			j=x/100
			y=1+j
			z=n*t
			k=y**z
			a=p*k
			c=a-p
			round1=round(c,2)
			round2=round(a,2)
			print ("Compound Interest is ")
			print (round1)
			time.sleep(1)
			print ("Amount after compounding is ")
			print (round2)
	elif calc=="cc":
		print ("Disclaimer: This conversion is valid according to the year 2021 and are subject to change as time passes")
		time.sleep(0.5)
		print ("valid currency conversions are:")
		time.sleep(0.5)
		print ("Enter 1 for INR to USD")
		time.sleep(0.5)
		print ("Enter 2 for INR to Australian Dollar")
		time.sleep(0.5)
		print ("Enter 3 for INR to EURO")
		time.sleep(0.5)
		print ("Enter 4 for INR to Pound")
		time.sleep(0.5)
		print ("Enter 5 for INR to YEN")
		time.sleep(0.5)
		print ("Enter 1* for USD to INR")
		time.sleep(0.5)
		print ("Enter 2* for Australian Dollar to INR")
		time.sleep(0.5)
		print ("Enter 3* for EURO to INR")
		time.sleep(0.5)
		print ("Enter 4* for Pound to INR")
		time.sleep(0.5)
		print ("Enter 5* for YEN to INR")
		time.sleep(0.5)
		curr=input("")
		if curr=="1":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			USD=INR*0.014
			print ("Your Amount in USD is",USD)	
		if curr=="2":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			AD=INR*0.018
			print ("Your Amount in Australian Dollar is",AD)
		if curr=="3":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			EURO=INR*0.011
			print ("Your Amount in EURO is",EURO)
		if curr=="4":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			P=INR*0.0098
			print ("Your Amount in Pound is",P)
		if curr=="5":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			YEN=INR*1.45
			print ("Your Amount in YEN is",YEN)
		if curr=="1*":
			usd=float(input("Enter the Amount in USD "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			INR=usd*72.55
			print ("Your Amount in INR is",INR)
		if curr=="2*":
			ad=float(input("Enter the Amount in Australian Dollar "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			INR=ad*57.1
			print ("Your Amount in INR is",INR)
		if curr=="3*":
			euro=float(input("Enter the Amount in Euro "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			INR=87.92*euro
			print ("Your Amount in INR is",INR)
		if curr=="4*":
			p=float(input("Enter the Amount in Pound "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			INR=p*101.68
			print ("Your Amount in INR is",INR)
		if curr=="5*":
			yen=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.25)
			print ("Calculating.")
			time.sleep(0.25)
			print ("Calculating..")
			time.sleep(0.25)
			print ("Calculating...")
			time.sleep(0.25)
			print ("Calculating....")
			time.sleep(0.25)
			print ("Calculating.....")
			time.sleep(0.25)			
			INR=yen*0.69
			print ("Your Amount in INR is",INR)
	else:
		print ("Cheking for invalid calculator")
		time.sleep(2)
		print ("Invalid calculator")
